# Generated by Django 6.0.3 on 2026-03-27 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('message', 'Message'), ('image', 'Image'), ('file', 'File'), ('video', 'Video'), ('reaction', 'Reaction'), ('reply', 'Reply')], default='message', max_length=20)),
                ('text', models.TextField(blank=True, default='')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='messaging.message')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
