# Generated by Django 6.0.3 on 2026-08-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('message', 'Message'), ('image', 'Image'), ('file', 'File'), ('video', 'Video'), ('reaction', 'Reaction'), ('reply', 'Reply'), ('mention', 'Mention')], default='message', max_length=20),
        ),
    ]
