# Generated by Django 6.0.3 on 2026-08-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_two_step_hint_user_two_step_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_visibility',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('nobody', 'Nobody')], default='everyone', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen_visibility',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('nobody', 'Nobody')], default='everyone', max_length=10),
        ),
    ]
