# Generated by Django 6.0.3 on 2026-08-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_avatar_visibility_user_last_seen_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='last_seen_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
