# Generated by Django 6.0.3 on 2026-08-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_usersession_last_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio_visibility',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('nobody', 'Nobody')], default='everyone', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='calls_visibility',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('nobody', 'Nobody')], default='everyone', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='forwarded_messages_visibility',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('nobody', 'Nobody')], default='everyone', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='invites_visibility',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('nobody', 'Nobody')], default='everyone', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='messages_visibility',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('nobody', 'Nobody')], default='everyone', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='voice_messages_visibility',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('nobody', 'Nobody')], default='everyone', max_length=10),
        ),
    ]
