# Generated by Django 6.0.3 on 2026-08-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_bio_visibility_user_calls_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_visibility',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('nobody', 'Nobody')], default='everyone', max_length=10),
        ),
    ]
