# Generated by Django 6.0.3 on 2026-03-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='scan_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
