# Generated by Django 6.0.3 on 2026-08-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_alter_message_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='call_duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='call_is_video',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='call_status',
            field=models.CharField(blank=True, choices=[('missed_or_canceled', 'Missed or canceled'), ('declined', 'Declined'), ('completed', 'Completed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('video', 'Video'), ('voice', 'Voice'), ('call', 'Call')], default='text', max_length=20),
        ),
    ]
