# Generated by Django 6.0.3 on 2026-03-23 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_alter_reaction_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
