# Generated by Django 6.0.3 on 2026-08-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_message_call_duration_seconds_message_call_is_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('video', 'Video'), ('voice', 'Voice'), ('call', 'Call'), ('system', 'System')], default='text', max_length=20),
        ),
    ]
