# Generated by Django 6.0.3 on 2026-08-24 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_alter_message_message_type_poll_polloption_pollvote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='allow_adding_options',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poll',
            name='allow_revoting',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poll',
            name='closes_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='poll',
            name='quiz_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poll',
            name='shuffle_options',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='polloption',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_poll_options', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='polloption',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
