# Generated by Django 6.0.3 on 2026-08-24 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0008_conversationparticipant_cleared_before_and_more'),
        ('messaging', '0010_bannedword_messagereport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['scheduled_at'], name='messaging_m_schedul_9cca01_idx'),
        ),
    ]
