# Generated by Django 6.0.3 on 2026-08-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0011_message_scheduled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='view_once',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
