# Generated by Django 6.0.3 on 2026-08-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0012_message_view_once_message_viewed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('video', 'Video'), ('voice', 'Voice'), ('call', 'Call'), ('system', 'System'), ('poll', 'Poll'), ('sticker', 'Sticker'), ('gif', 'Gif')], default='text', max_length=20),
        ),
    ]
