# Generated by Django 6.0.3 on 2026-08-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparticipant',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
