# Generated by Django 6.0.3 on 2026-08-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_chatfolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='type',
            field=models.CharField(choices=[('private', 'Private'), ('group', 'Group'), ('channel', 'Channel')], default='private', max_length=20),
        ),
    ]
