# Generated by Django 6.0.3 on 2026-08-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_alter_conversation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='invite_slug',
            field=models.SlugField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
