# Generated by Django 6.0.3 on 2026-08-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0006_conversation_invite_slug_conversation_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='auto_delete_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
