# Generated by Django 6.0.3 on 2026-08-25 05:22

import apps.conversations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0008_conversationparticipant_cleared_before_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparticipant',
            name='wallpaper_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.conversations.models.participant_wallpaper_path),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='wallpaper_type',
            field=models.CharField(choices=[('default', 'Default'), ('preset', 'Preset'), ('image', 'Image')], default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='wallpaper_value',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
